CREATE STREAM WINLOGBEAT (
    "@timestamp" VARCHAR,
    "@metadata" STRUCT<
        beat VARCHAR,
        type VARCHAR,
        version VARCHAR>,
    agent STRUCT<
        ephemeral_id VARCHAR,
        id VARCHAR,
        name VARCHAR,
        type VARCHAR,
        version VARCHAR>,
    winlog STRUCT<
        process STRUCT<
            pid INT,
            thread STRUCT<
                id INT>>,
        api VARCHAR,
        keywords ARRAY<STRING>,
        channel VARCHAR,
        record_id INT,
        task VARCHAR,
        opcode VARCHAR,
        user STRUCT<
            type VARCHAR,
            identifier VARCHAR,
            domain VARCHAR,
            name VARCHAR>,
        event_id VARCHAR,
        event_data VARCHAR,
        computer_name VARCHAR,
        provider_guid VARCHAR,
        provider_name VARCHAR>,
    event STRUCT<
        created VARCHAR,
        code VARCHAR,
        kind VARCHAR,
        provider VARCHAR,
        action VARCHAR>,
    log STRUCT<
        level VARCHAR>,
    message VARCHAR,
    host STRUCT<
        name VARCHAR,
        hostname VARCHAR,
        architecture VARCHAR,
        os STRUCT<
            platform VARCHAR,
            version VARCHAR,
            family VARCHAR,
            name VARCHAR,
            kernel VARCHAR,
            build VARCHAR,
            type VARCHAR>,
        id VARCHAR,
        ip ARRAY<VARCHAR>,
        mac ARRAY<VARCHAR>>,
    ecs STRUCT<
        version VARCHAR>) 
WITH (KAFKA_TOPIC='winlogbeat', VALUE_FORMAT='JSON');