iCREATE STREAM SYSMON_SSL WITH (KAFKA_TOPIC='sysmon_ssl', VALUE_FORMAT='JSON') AS
SELECT 
CONCAT(FORMAT_TIMESTAMP(FROM_UNIXTIME(CAST(ROUND((SSL_TS * 1000), 0) AS BIGINT)), 'yyyy-MM-dd HH:mm:ss.SSS', 'UTC'), ' UTC') AS ZEEK_TIMESTAMP, 
s.SRC_HOSTNAME AS SRC_HOSTNAME,
e.SRC_IP AS SRC_IP,
s.SRC_PORT AS SRC_PORT,
s.DEST_HOSTNAME AS DEST_HOSTNAME,
e.DEST_IP AS DEST_IP,
e.DEST_PORT AS DEST_PORT,
e.SUBJECT AS SUBJECT,
e.SERVER_NAME AS SERVER_NAME,
e.CERT_REGISTRATION_DATE AS CERT_REGISTRATION_DATE,
e.CERT_EXPIRATION_DATE AS CERT_EXPIRATION_DATE,
s.USER AS USER,
s.FILE,
s."@timestamp" AS SYSMON_TIMESTAMP
FROM ENRICHED_SSL e 
INNER JOIN SYSMON_NETWORK s WITHIN 1 SECONDS on e.SRC_PORT = s.SRC_PORT
EMIT CHANGES;
