CREATE STREAM SYSMON_NETWORK WITH (KAFKA_TOPIC='sysmon_network', VALUE_FORMAT='JSON', PARTITIONS='6') AS
SELECT 
*, 
EXTRACTJSONFIELD(WINLOG->EVENT_DATA, '$.SourceHostname') AS SRC_HOSTNAME,
EXTRACTJSONFIELD(WINLOG->EVENT_DATA, '$.SourceIp') AS SRC_IP,
CAST(EXTRACTJSONFIELD(WINLOG->EVENT_DATA, '$.SourcePort') AS INT) AS SRC_PORT,
EXTRACTJSONFIELD(WINLOG->EVENT_DATA, '$.DestinationHostname') AS DEST_HOSTNAME,
EXTRACTJSONFIELD(WINLOG->EVENT_DATA, '$.DestinationIp') AS DEST_IP,
CAST(EXTRACTJSONFIELD(WINLOG->EVENT_DATA, '$.DestinationPort') AS INT) AS DEST_PORT,
EXTRACTJSONFIELD(WINLOG->EVENT_DATA, '$.User') AS USER,
EXTRACTJSONFIELD(WINLOG->EVENT_DATA, '$.Image') AS FILE
FROM WINLOGBEAT
WHERE WINLOG->EVENT_ID = '3' 
EMIT CHANGES;
