title: Possible Data Collection Over SMB
description: 'Many different files accessed over SMB by a single IP in a short amount of time. Not only could this be This potential data collection, but could also detect scenario of ransomware. This Sigma query is designed to accompany the Corelight Threat Hunting Guide, which can be found here: https://www3.corelight.com/corelights-introductory-guide-to-threat-hunting-with-zeek-bro-logs'
author: SOC Prime Team
tags:
  - attack.collection
  - attack.t1039
logsource:
  product: zeek
  service: smb_files
detection:
  name_exists:
    name: '*'
  pre_filter:
    name: '<share_root>'
  timeframe: 1m 
  condition: name_exists AND NOT pre_filter | count(name) by id_orig_h > 50
falsepositive:
  - 'Mistakenly opening many files at one time. Should be rare'
  - 'File server to file server replication'
fields:
  - ts
  - id.orig_h
  - id.orig_p
  - id.resp_h
  - id.resp_p
  - name
  - path
  - prev_name
  - size
  - times_accessed
  - times_changed
  - times_created
  - times_modified
  - fuid
  - uid